// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package versions

import (
	"database/sql"
)

type SemanticVersion struct {
	ID          uint64
	Project     string
	Major       int32
	Minor       int32
	Patch       int32
	CommitHash  string
	CreatedAt   sql.NullTime
	Description sql.NullString
}
